### ISSUE TITLE
createNode如果多次创建不释放 占用内存太大，

### ISSUE THREAD

**Issue by xukun311** [wangjia184/sortedset#10]
func createNode(level int, score SCORE, key string, value interface{}) *SortedSetNode {
	node := SortedSetNode{
		score: score,
		key:   key,
		Value: value,
		level: make([]SortedSetLevel, level),  // 默认是32？ 这里有没有优化余地？
	}
	return &node
}

**Comment by wangjia184** [comment]
No,  you dont understand how SkipList nodes are organized. 
There is no default value.   The head/tail tower are created with full height,  because they need be connected to all levels.
While the height of intermediate nodes between them are determined by probability.  The probability is very low to create a full height node
